/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0/samples
 */
plugins {
   java 
}
repositories {
    mavenCentral() 
}

dependencies {
    implementation("io.projectreactor:reactor-core:3.5.4");
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("org.jetbrains:annotations:23.0.0")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
}
